title: "Your name"
body:
    - type: markdown
      attributes:
          value: |
              Steps
              =====

              1. :pencil: Update the resume with your data.
              1. :point_down: Click in the green button bellow (**Start discussion**) to save your resume.
              1. :white_check_mark: Open [Action section](https://github.com/shield-wall/myprofile/actions/workflows/resume.yaml) in a new tab, and click on Resume process.(probably it's the first one).
              1. :clock1: Wait until the process finish, and you will see a resume link on footer page.

              > **Note**
              > 
              > After you have the resume created, when you update **discussion's description** a new resume will be generate :white_check_mark:.

    - type: textarea
      id: improvements
      attributes:
          label: Resume structure
          description: "Please update the default values with your data."
          value: |
              ```yaml
                    basic:
                        firstName: John
                        lastName: Doe
                        photoUrl: https://avatars.githubusercontent.com/u/6358755?v=4
                        position: Software Developer
                    
                    sectionOne:
                        #[about section]
                        -   title: About
                            icon: fileDescription
                            children:
                                -   content: |
                                        About me profile :)
                    
                                         - item **1**
                                         - item 2
                                         - item 3
                    
                        #[experience section]
                        -   title: Experiences
                            icon: work
                            children:
                                -   company: Company A
                                    position: Developer
                                    timePeriod: since January 2016
                                    description: |
                                        ***Programming and watching cute cat videos.**
                    
                                        1. item1
                                        1. item2
                                        1. item3
                                    website: https://example.com
                                    photoUrl: https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png
                    
                                -   company: Company B
                                    position: Frontend Developer
                                    timePeriod: January 2015 - December 2015
                                    description: Fulfillment of extremely important tasks.
                                    website: https://example.com
                                    photoUrl: https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png
                    
                                -   company: Company C
                                    position: Trainee
                                    timePeriod: March 2014 - December 2014
                                    description: Making coffee and baking cookies.
                                    website: ~
                                    photoUrl: ~
                    
                        #[certification section]
                        -   title: Certifications
                            icon: certification
                            children:
                                -   title: Master of Arts
                                    photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
                                    timePeriod: March 2012 - December 2013
                                    website: ~
                    
                                -   title: Master of Arts
                                    photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
                                    timePeriod: March 2012 - December 2013
                                    website: ~
                    
                    sectionTwo:
                        #[skill section]
                        -   title: ~
                            icon: ~
                            children:
                                -   tag: HTML5
                                -   tag: CSS3
                                -   tag: JavaScript
                                -   tag: Node.js
                    
                        #[contact section]
                        -   title: ~
                            icon: ~
                            children:
                                -   title: +49 123456789
                                    icon: phone
                    
                                -   title: email@gmail.com
                                    icon: email
                    
                                -   title: https://linkedin.com/eerison
                                    icon: linkedin
                    
                                -   title: https://github.com/eerison
                                    icon: github
                    
                        #[education section]
                        -   title: Education
                            icon: education
                            children:
                                -   degree: Master of Arts
                                    institution: Harvard
                                    timePeriod: March 2012 - December 2013
                    
                                -   degree: Bachelor of Science
                                    institution: Harvard
                                    timePeriod: March 2009 - December 2011
                    
                        #[language section]
                        -   title: Language
                            icon: language
                            children:
                                -   tag: ['English', 'Intermediate']
                                -   tag: ['Portuguese', 'Native']
            
            ```
      validations:
          required: true
